# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: none

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - SPELL

DISABLE_LINTERS:
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

REPOSITORY_KICS_CONFIG_FILE: kics.yaml
PYTHON_BANDIT_FILTER_REGEX_EXCLUDE: test
EDITORCONFIG_EDITORCONFIG_CHECKER_CONFIG_FILE: .editorconfig-checker.json
