name: Build
on:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        poetry-version: [ "1.8.5", "latest" ]
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Define a cache for the virtual environment based on the dependencies lock file
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install Requirements
        run: poetry install --sync --no-interaction
      - name: Build
        run: poetry build
#      - name: Test
#        run: poetry run pytest -v
