name: Release
on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: read

jobs:
  ci:
    runs-on: "ubuntu-latest"
    environment:
      name: pypi
      url: https://pypi.org/project/enpass2onepassword/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Load the cache
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('uv.lock') }}
      - name: Install the project
        run: uv sync --all-extras --no-dev
      - name: Build the project
        run: uv build
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
