name: Release
on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: read

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
    runs-on: ${{ matrix.os }}
    environment:
      name: pypi
      url: https://pypi.org/project/enpass2onepassword/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: "1.8.5"
      - name: Define a cache for the virtual environment based on the dependencies lock file
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install Requirements
        run: poetry install --sync --no-interaction
      - name: Build
        run: poetry build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
